### PR TITLE
Divergence from reference

### PR DESCRIPTION
**Pull request by hardingnj**
Work to calculate distance of different parts of genome from ref sequence via @EricRLucas 
re #32

### CODE REVIEW

**Comment by EricRLucas** [comment]
I've changed the script to output jpg files. Do I need to start a new pull request for this? The colours for each population are currently arbitrary, but should be easy to change to standard population colours.

**Comment by alimanfoo** [comment]
Thanks @EricRLucas. You can just push more changes to the ``refdiff`` branch, they'll show up in this PR.

**Comment by EricRLucas** [comment]
OK. I've done that but it doesn't appear to have shown up on this thread

**Comment by alimanfoo** [comment]
Hi Eric. Here's my usual git workflow, from the beginning of working on a new task - maybe something in here that was missed...

```
# before start working on a new task, make sure master branch is up to date
git checkout master
git pull
# start working on a new task - create a branch with name representing the task (e.g., "refdiff")
git checkout -b refdiff  # create a local branch named "refdiff"
git push -u origin refdiff  # create a remote branch named "refdiff" on github and link local and remote branches
# do some work, then add, commit and push new/changed files
git add some-file-i-made-or-changed.txt
git commit -m 'i made some changes to blah blah'
git push origin refdiff  # or just git push will work if you've properly linked local and remote branches
# go to github and make a PR from refdiff to master
```

**Comment by cclarkson** [comment]
superceded by #67

**Pull request closed without merging**
