### PR TITLE
WIP - possible titles - please add suggestions

### PR DESCRIPTION
**Pull request by cclarkson**

### CODE REVIEW

**Comment by EricRLucas** [comment]
The Anopheles gambiae 1000 Genomes project Phase2. Addition of new populations reveals ...

The Anopheles gambiae 1000 Genomes project Phase2. Genomic resource expanded to 1142 mosquitoes and X populations.

The Anopheles gambiae 1000 Genomes project Phase2. Whole-genome sequencing of 1142 mosquito genomes indicates areas of possible pyrethroid bednet failure  [I think this one is too bold, but chucking it in in case a variant of it might still work]

**Comment by cclarkson** [comment]
Ag1000g Phase 2 - Genetic variation, population structure and insecticide resistance from 1142 malaria vector genomes.

**Comment by hardingnj** [comment]
Whole-genome sequencing of 1142 mosquito genomes reveals heterogeneity of insecticide resistance
Whole-genome sequencing of 1142 mosquito genomes and implications for malaria control

**Comment by alimanfoo** [comment]
I'm going to close this one for now but happy to revisit if anyone has strong feelings.

**Pull request closed without merging**
