### PR TITLE
Adds all phase 2 vgsc IR SNP/CNV counts to supplementary tables

### LINKED ISSUE #225: IR genotypes file for data release
I think we need to add cyp CNV presence/absence to this table due to figure 6.

### PR DESCRIPTION
**Pull request by cclarkson**
resolves #225

### CODE REVIEW

**Comment by cclarkson** [comment]
Hi @alimanfoo @EricRLucas  - this is ready for review now.

**Comment by cclarkson** [comment]
@EricRLucas, nope it's because I've missed off the index when building the csv - thanks for spotting - should be fixed now.

**Comment by cclarkson** [comment]
@EricRLucas, they're sorted by country then by collection site I think. So is the meta data document, but these could both be changed to ox_code alphabetical if you think that makes it more intuitive?

I'll add the sex column back in now.

Chris

**Comment by EricRLucas** [comment]
Re: sorting. I'm not fussed as long as they are sorted by some criterion. The metadata files that I've used in the past (and the one on the FTP site) for phase 2 were always sorted alphanumerically, so all the output I've produced has been sorted that way. But sorting by collection site is also a pretty sensible way of doing things.

**Comment by cclarkson** [comment]
@EricRLucas  - to be honest, I prefer alphanumerically as it is what I would presume they would be if I didn't know better (and a quick glance might lead you think that too).
I'll sort this file here and then have a look for other files that need sorting.

**Comment by cclarkson** [comment]
@EricRLucas  - actually they should be sorted in the same order as the variant data files  - so alphanumeric ox_code it is. Ready for review.

**Comment by alimanfoo** [comment]
Hi @cclarkson, I've pushed a couple of commits to this PR. The first does some refactoring of the notebook that generates the IR table, just for ease of maintenance. The second adds a simple notebook to check some of the IR results. 

The results for the pyrethroid resistance genotypes look good, the numbers I get match with the pie charts in your pyrethroid resistance figure. 

However, for Ace1, the numbers don't match with the figure you sent me for PAMCA. In your figure G119S and the CNV were in perfect LD, i.e., everyone was always both or neither. However I find plenty of individuals with G119S alone or a CNV alone. 

Can we have a quick call this avo to talk through? Ta.

**Comment by cclarkson** [comment]
Hi @alimanfoo, happy to chat whenever you are free. I wonder if this is a legacy of the meta data file that was sorted incorrectly. At some point, when new columns were added, it got sorted by sample site - I thought I'd caught all the broken code but this may have slipped through. I'll have a look at this now, make sure the updated meta data is being used and see if anything changes.

**Comment by alimanfoo** [comment]
FWIW the ace1 figure did seem a bit too perfect. It seems more plausible to me that there isn't perfect LD between CNV and G119S. I wonder if there was a bug in the plotting code?

**Comment by cclarkson** [comment]
@alimanfoo - I'll go through the supplementary file code first, then check out the plot.

**Comment by cclarkson** [comment]
Hi @alimanfoo - I've made a new commit that I think fixes the problem, this was due to the meta data order. 

The numbers in the checking notebook now look as expected. There was never complete LD between CNV and Ace SNP but IIRC there was only be a handful of samples in the whole cohort where it's not the case - this looks correct now.

It's worth making sure that any instances of your phase 2 meta data are ordered by ox-code rather than country-location-site-ox-code. The correct file should be on the ftp.

**Comment by alimanfoo** [comment]
@cclarkson OK, thanks. Confirm the ace1 numbers look better, matching your figure.

But the new vgsc data doesn't quite match the pyrethroid_resistance_simplified.jpg figure. E.g., the numbers for GHgam don't match. Does that figure need to get regenerated?

**Comment by alimanfoo** [comment]
@cclarkson btw in the notebook I edited the calldata path back to "calldata/GT" as per the new zarr data - in your original notebook you had it as "calldata/GT" in some places and "calldata/genotype" in other places, so I guess you must have access to the new zarr data.

**Comment by alimanfoo** [comment]
> But the new vgsc data doesn't quite match the pyrethroid_resistance_simplified.jpg figure. E.g., the numbers for GHgam don't match. Does that figure need to get regenerated?

Sorry, just saw #250.

**Comment by alimanfoo** [comment]
OK, I think we're good to go here, merging.

**Pull request merged**
