### PR TITLE
PCA artwork

### LINKED ISSUE #38: PCA artwork

### PR DESCRIPTION
**Pull request by cclarkson**
As suggested by @EricRLucas I have split the PCA artwork into two figures. The 'main text' artwork shows the first four PCs, as these have the interesting features pertaining to the new phase 2 populations. The 'supplementary' artwork shows the % variance explained and the next four PCs.

https://github.com/malariagen/ag1000g-phase2-data-paper/blob/78a5ca34124dfec16cc057f85dd176b6432a1004/notebooks/Phase_2_3L_main_text_pca.jpeg?raw=true

https://github.com/malariagen/ag1000g-phase2-data-paper/blob/78a5ca34124dfec16cc057f85dd176b6432a1004/notebooks/Phase_2_3L_supplementary_pca.jpeg?raw=true

resolves #38

### CODE REVIEW

**Comment by hardingnj** [comment]
Also needs to be adapted once #88 is merged.

**Comment by cclarkson** [comment]
Hi @hardingnj, what adaptation will be required after the binder update?

**Comment by EricRLucas** [comment]
Just having a go at drafting the narrative and I can't tell from the PCAs where the BFgam samples cluster (I'm guessing they are underneath some of the other samples). Any ideas?

**Comment by hardingnj** [comment]
This is where: http://hardingnj.github.io/2018/08/15/making-interactive-pca-plots.html might be useful!

**Comment by EricRLucas** [comment]
That's very cool. I don't suppose that plots like this can be incorporated into a pdf? If so, we could even include an second version of the main plots in Supp Mat that the reader can play with.

**Comment by hardingnj** [comment]
Actually Chris, I think it's fine in a single part- but it should include a check for a cached `.npy` file, so you can run the whole thing if you want, and equally don't have to worry about just running parts of the notebook.

**Comment by cclarkson** [comment]
@hardingnj, @EricRLucas,

Changes made, setup.ipynb updated, bokeh interaction added. Ready for review.

**Comment by hardingnj** [comment]
Hi @cclarkson, please shout if you have issues resolving the conflict in `setup.ipynb`

**Comment by cclarkson** [comment]
Thanks @hardingnj 

I have taken on all suggestions except for the `tempfile`, if I need to make changes to the pca I'd like that file to hang around, LD pruning takes hours, I'd rather have to manually delete it when I'm finished.

Also, `locate_range` is not a function available to that structure so I left it as `locate_keys`.

If there are no more comments I will merge this tomorrow.

**Comment by hardingnj** [comment]
Cool- no worries. You should have `locate_range()` if it's a `allel.SortedIndex` though.

**Pull request merged**
