### PR TITLE
haplotype validation work

### LINKED ISSUE #29: Phasing artwork: update phase 1 plots with new crosses.

### PR DESCRIPTION
**Pull request by hardingnj**
Resolves #29

### CODE REVIEW

**Comment by hardingnj** [comment]
This is ready for review

**Comment by cclarkson** [comment]
@hardingnj - on this - just need to download some data to run the notebook!

**Comment by cclarkson** [comment]
@hardingnj,

I'm getting an issue that I have had before but you are clearly not - when you call 

`genome = phase2_ar1.genome_agamp3`

you get something sensible, e.g. the keys are '2L', '2R' etc. but I get this:
```
['UNKN chromosome:AgamP3:UNKN:1:42389979:1',
 '3R chromosome:AgamP3:3R:1:53200684:1',
 '3L chromosome:AgamP3:3L:1:41963435:1',
 '2R chromosome:AgamP3:2R:1:61545105:1',
 '2L chromosome:AgamP3:2L:1:49364325:1',
 'Y_unplaced chromosome:AgamP3:Y_unplaced:1:237045:1',
 'X chromosome:AgamP3:X:1:24393108:1']
```
Is your reference genome better than mine?!

**Comment by hardingnj** [comment]
I think this should be fixed automatically if you delete the additional files around the fasta. Then try reindexing it with `samtools faidx {fasta}`. 
`pyfaidx` should pick it up automatically

**Comment by hardingnj** [comment]
I'm not sure really... generally I try to keep data out of the repo. Maybe we can add it to the release if it's important. I think that's the better solution actually.

**Pull request merged**
