### PR TITLE
IBD analysis  new method using sliding size window

### PR DESCRIPTION
**Pull request by hardingnj**
This is some work to add the type of plot that Andy suggested on the call last week. 

For each size threshold I create a summary stat for each population. Here I show the median IBD sum between each comparison. Although this could be mean IBD count for example. 

I think it looks reasonable, and has the advantage it would make sense if much smaller, if it needs to be placed in a panel etc.
image

### CODE REVIEW

**Comment by cclarkson** [comment]
Hi @hardingnj, it looks nice but is less intuitive (to me at least). Cameroon stood out as interesting in the previous version but does not here, why is that?

**Comment by hardingnj** [comment]
That's a fair point! Because this plot is based on a summarization of the data. In this case the median. 

You can kind of see that cameroon has lots of small IDB chunks as there is a steep drop initially from 10^3 to 10^4. 

Agree it's less intuitive though.

**Comment by cclarkson** [comment]
Ah yes, see in now. It will take some explaining in the text and I'm not sure it can be made much smaller as that kind of detail will become hard to see.

From this plot I'm getting Kenya/Gabon (as per usual) and The Gambia which is interesting particularly the distance from Guinea Bissau which I'd missed in the previous version (but I can see it now I'm looking!).

I really like the splodge of colour in the first version but I am happy to be convinced this is better.

**Comment by hardingnj** [comment]
Agreed. I think the first is better- but I think this is an option if we are super space limited and need to condense.

**Pull request merged**
