### PR TITLE
Pyrethroid resistance genotype map - draft

### LINKED ISSUE #127: Insecticide resistance

### PR DESCRIPTION
**Pull request by cclarkson**
resolves #127 

Opinions please!

### CODE REVIEW

**Comment by EricRLucas** [comment]
Agree with Nick about red and blue, but not sure what alternatives to suggest, as the red/blue have the advantage that they work well with their intermediate (purple), which can then be used to show presence of both. Yellow is just a bit rubbish on plots. Could maybe go for due lighter tone colours for each of kdr / cyp and a darker tone for both?

**Comment by cclarkson** [comment]
I'll try blue/yellow/green.
I'll also split up the cyps to see if there is an interesting distribution of cyp6 and cyp9.

**Comment by EricRLucas** [comment]
You tend to get cyp9k1 in gambiae and cyp6 in coluzzii (apart from Uganda)

**Comment by cclarkson** [comment]
@EricRLucas  ***SPOILER ALERT***

**Comment by EricRLucas** [comment]
:-)

**Comment by hardingnj** [comment]
- I think the purple/yellow is best. 

- Test wise I think _kdr only_ reads better than _just kdr_.

Something else we should thing about is an alternative to pies. Perhaps a "waffle chart" like this, where 1 square is one mosquito:
image

Then also, I thought about this 

t
Which is a way of handling cases where you want to display 3 genes. You have to perform a sequental index sort of rows.

**Pull request merged**
