### PR TITLE
Resource page - pipeline methods file

### PR DESCRIPTION
**Pull request by cclarkson**
If we're happy with this format and the phasing details are correct I will add citations and we can merge.

### CODE REVIEW

**Comment by cclarkson** [comment]
Nice to have but not priority - need cnv methods too (@EricRLucas)

**Comment by EricRLucas** [comment]
@cclarkson No worries. Presumably we don't want to repeat all the CNV methods in their entirety since they are already in the CNV paper. Roughly how much detail should I go into?

**Comment by cclarkson** [comment]
@EricRLucas, what we are trying to achieve is all of the 'pipeline' methods ending up in a single document that someone can access alongside the data. Currently the P2 manuscript  just refers back to the P1 paper and your CNV paper. Here I've taken the methods from the P1 supplementary documentation and updated them to fit P2. I think for CNV methods, the bits referring to generating the calls could be taken straight from the paper - the relevant papers will then be referenced and this document will live on the ftp as a one stop shop.

**Comment by EricRLucas** [comment]
Cool, no worries. I'm losing behind on a couple of tasks that I should have done this week and which will take priority early next week, but should be able to do it by end of next week if that's ok.

**Comment by cclarkson** [comment]
Hi @hardingnj, could you check if the phasing methods here are correct for phase 2?

Thanks

**Comment by cclarkson** [comment]
@alimanfoo - this is ready for review now.

**Pull request merged**
