### PR TITLE
updated phasing validation

### PR DESCRIPTION
**Pull request by hardingnj**
New plots based on qual filtering threshold of GQ=40

Updated plots so that we don't have wasted space, maternal/paternal each have their own variant locator

### CODE REVIEW

**Comment by cclarkson** [comment]
Hi @hardingnj, ready for review or WIP?

**Comment by hardingnj** [comment]
Sort of WIP- but would be good to get it merged as I have another branch based off this one.

**Comment by cclarkson** [comment]
Hi @hardingnj, in each figure, the x-axis numbering of the top panel is just visible poking out from behind the bottom panel. Could you easily remove the axis labelling from the top plot?

**Comment by hardingnj** [comment]
Well spotted- yes I can do that easily enough

**Comment by hardingnj** [comment]
Just to record here, as I think I said on a phone call recently, I'm planning to totally rerun the validation, including the evaluation from scratch. 

I'll rename this to make clear it's WIP. Then the recombination is contingent on this.

**Comment by hardingnj** [comment]
This is ready for review now- sorry for the delay! A bit trickier than I thought in places.

**Comment by cclarkson** [comment]
LGTM :+1:

**Pull request merged**
