### PR TITLE
WIP sample collection table

### PR DESCRIPTION
**Pull request by cclarkson**
I think I've got the columns sorted - opinions on changes gratefully received. 

I'm just playing with panda.to_latex output now, if that doesn't work I will fall back to the latex table methods we have used before.

### CODE REVIEW

**Comment by cclarkson** [comment]
How do folk feel about this?

table1

**Comment by EricRLucas** [comment]
Looks great Chris, thanks. The only minor thing I would suggest is to make it clear that the numbers in the last three columns are numbers of mosquitoes. But that can probably go in the caption.

**Comment by cclarkson** [comment]
Hi @EricRLucas,

Could change the upper column label to "Anopheles species counts"  or "Anopheles species frequencies" or something like that, what do you think?

**Comment by EricRLucas** [comment]
"Anopheles species counts" works for me

**Comment by cclarkson** [comment]
Table column header changed as per @EricRLucas's suggestion.

Species now pulled from meta data input. @hardingnj, I have done this by looping though the data in a less than elegant fashion. I think it can be done using the groupby series but I had trouble working with the output - any suggestions/examples (perhaps we could discuss next time I'm over?).

test_table_2

**Comment by hardingnj** [comment]
This was fun: I learnt something new about how this works.

```
# First fill unknowns
df_meta.m_s.fillna("unknown", inplace=True)
```

```
# crosstab works, but can't handle the multiindex
pd.crosstab(df_meta.site, df_meta.m_s, dropna=False)
```
or

```
# groupby can, but is a bit more involved
count_g = df_meta.groupby(["location", "site"]).m_s.value_counts()
count_g.name = "count"

count_g.reset_index().pivot_table(
    values="count", 
    columns="m_s", 
    index=["location", "site"]).fillna(0).astype("int")
```

**Comment by cclarkson** [comment]
Thanks @hardingnj, I have had a play with your examples and I've gone with the second as the output is easier to integrate. I've left all the different methods in the notebooks with annotations.

I you could give this another review, I will merge. 

Cheers

**Pull request merged**
