### PR TITLE
11 field pop sampling methods

### PR DESCRIPTION
**Pull request by cclarkson**
I have entered the text for the novel phase 2 population collection info, set-up the ref.bib and added the author list. 

Might be good to review this and merge first, then Nick's PR second?

### CODE REVIEW

**Comment by EricRLucas** [comment]
Hi Chris,

Thanks for this, looks great. Many thanks for this. There are only a few things I would suggest. 

1. Does it make sense to start the line about Mayotte with "France". It might be a bit confusing. Would it make more sense to call it Mayotte Island or similar? 

2. Since all but one population was extracted with DNeasy kit, would it make sense to have a line at the start along the lines of "unless stated otherwise, all samples were extracted using DNeasy ...".? 

3. Showing my ignorance of the pipeline, but was any attempt made pre-sequencing to species ID the samples from the difficult populations? If so, is this worth mentioning? Also, some populations (eg: CI) just have species ID data without saying how this was obtained.

**Comment by EricRLucas** [comment]
Just checked with Dave. They were ID'd as coluzzii rather than gambiae ss using SINE PCR. Sounds like Scott et al wasn't run.

**Comment by cclarkson** [comment]
Cheer @EricRLucas 

I've made some changes based on your suggestions, could you give it a once over and approve the PR if you're happy.

**Comment by EricRLucas** [comment]
I'm failing at GitHub again. I found the files last time by clicking on the link in the text "Add more commits by pushing to the 11_field_pop_sampling_METHODS branch on cclarkson/ag1000g-phase2-data-paper.". If I do that again now, I just get the version from 2 days ago.

**Comment by cclarkson** [comment]
I always find that with the web interface, going back out to the main ag1000g-phase2... front, then clicking on the issue again will update what you can see.

**Comment by cclarkson** [comment]
You're not going mad (I may be) - the push didn't work for some reason!
The new versions should be there now.
Apologies!

**Pull request merged**
