### PR TITLE
Contributing partner studies document

### LINKED ISSUE #223: Resource page - samples contributor details file
Need to take from both phase 1 and 2 papers.

### PR DESCRIPTION
**Pull request by cclarkson**
resolves #223 

Adds a pdf with sample collection and contributor info for all samples included in phase 2. This is chimera of this info from the phase 1 supplementary and phase 2 methods.

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hey @cclarkson, I've done some editing of this doc, mainly to bring it stylistically closer to the equivalent doc for PF6. There are a couple of @@TODO mainly to add any additional people from the new phase 2 studies, but I think this is good enough to show tomorrow. I've attached here:

[Ag1000G_phase_2_partner_studies.docx](https://github.com/malariagen/ag1000g-phase2-data-paper/files/3704775/Ag1000G_phase_2_partner_studies.docx)

...would you be able to grab this, fill in any @@TODO, then update this PR with the new file? Ta.

**Comment by cclarkson** [comment]
@alimanfoo - I've noticed you've added a few references to this document, is the intention to add them all?

**Comment by cclarkson** [comment]
@alimanfoo  - I've added all the citations too.

**Comment by alimanfoo** [comment]
Hi @cclarkson, the idea of adding the references subsections was to provide a reference that specifically describes work done by the partner study. I.e., it's a way to provide some prominence for the research outputs of the partner study itself. 

So those references subsections should only contain a reference if it's an output of the partner study. We probably should include other references, but they should go somewhere else so it doesn't get confusing about what is an output of the partner study versus what is a general reference to a method or someone else's work.

How about, within each partner study, change the sub-heading "References" to "Publications". Then create a new "References" heading at the end of the document and move all the references that you've added to that section at the end.

**Comment by cclarkson** [comment]
Hi @alimanfoo, I've moved the 'References' down to the end of the document but I am a bit unclear what constitutes a submission specific 'Publication' - the Guinea-Bissau Vincente paper is obviously one, but the others that you have added to the previous version  e.g. Lobo/Pinto - are not publications using these data are they?

**Comment by alimanfoo** [comment]
Hi Chris, no they are not publications using the Ag1000G data, they are
publications about the original research study that was collecting the
samples.

**Comment by alimanfoo** [comment]
I made some light edits to restore publications for Cameroon and Guinea studies. Think this is good to go, merging.

**Pull request merged**
