### PR TITLE
Insecticide resistance map update

### LINKED ISSUE #140: Insecticide resistance map - update
1. remove complex map colouring - monochrome or much simplified colours
2. try making it half column width
3. pies can all be the same size
4. clean up label positions
5. legend label should make clear that cyps are duplications

### PR DESCRIPTION
**Pull request by cclarkson**
Reduces size to single column, makes all pies same size, fixes map, fixes labels and legend.

Resolves #140

### CODE REVIEW

**Comment by cclarkson** [comment]
Hi @hardingnj 

- Cheers, the black dot is an island. I have spent some time fiddling to cover it but it is a pain, happy to do so once everyone is cool with the plot!
- Will change "just" to "only".
- Could you explain why amplification is better than duplication?

Thanks

**Comment by hardingnj** [comment]
Because I think duplication implies x2 (??), but I'm happy to be wrong on this!

**Comment by EricRLucas** [comment]
I agree that amplification is technically more correct than duplication, for the reason Nick says. But readers might find "duplication" a clearer term? I would probably vote for "amplification" but would cave in relatively easily is someone pushed back on this.

**Comment by cclarkson** [comment]
Ah, yes, makes sense, thanks @hardingnj !

Also, as @EricRLucas  is the king of ~~duplications~~ amplifications, I will bow to his will.

**Comment by alimanfoo** [comment]
Figure looks great :+1: 

For the legend, how about:

**Pyrethroid resistance genotype**
* *kdr*
* P450 amplification
* *kdr* and P450 amplification

(Then explain in the figure caption that "kdr" means at least one allele either L995S or L995F, and "P450 amplification" means an amplification at any gene in cyp6p/aa cluster or cyp9k1.)

May need to make a bit of room to fit the slightly longer legend labels in. Also might look good to make the font size for the legend and the pie labels a bit closer, legend is currently a bit in your face.

**Comment by cclarkson** [comment]
@EricRLucas, @hardingnj - this is ready for a last review.

**Pull request merged**
